# Generated by Django 5.0.3 on 2024-04-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('letterset', models.CharField(max_length=7)),
                ('multiplayer', models.BooleanField()),
                ('timeout', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('welcome', 'welcome'), ('playing', 'playing'), ('waiting', 'waiting'), ('ended', 'ended')], default='playing', max_length=20)),
                ('players', models.ManyToManyField(to='game.playermodel')),
            ],
        ),
    ]
