# Generated by Django 5.0.3 on 2024-04-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamemodel_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='players',
            field=models.ManyToManyField(to='game.playermodel'),
        ),
    ]
